### ISSUE TITLE
Provide a mechanism to define the suggested prompt for image descriptions in settings.

### ISSUE THREAD

**Issue by rperez030** [AAClause/nvda-OpenAI#17]
Being able to combine text and images as part of the user prompt is very powerful, but at least for me, the default suggested prompt ("Describe the images in as much detail as possible.") gets on the way because, most of the times, I have a different request in mind. this suggested prompt should be editable / translatable by the user or removed entirely if needed.

**Comment by Nael-Sayegh** [comment]
Hello,
Your idea is very interesting, I am currently working on this feature.
