### ISSUE TITLE
Error in image description with gpt-4-vision-preview module

### ISSUE THREAD

**Issue by muhammadGagah** [AAClause/nvda-OpenAI#24]
Hi, I have gpt-4-vision API access, but error when using this add-on, here's what I got from the NVDA logs:
ERROR - unhandled exception (14:26:17.842) - MainThread (7056):
Traceback (most recent call last):
  File "C:\Users\muham\AppData\Roaming\nvda\addons\OpenAI\globalPlugins\openai\maindialog.py", line 732, in OnResult
    historyBlock.temperature = int(self.conf["temperature"]) / 100
  File "config\__init__.pyc", line 1123, in __getitem__
KeyError: 'temperature'

**Comment by MuhammadGagah** [comment]
Well, this doesn't show any more errors, and is functioning as it should.

**Comment by MuhammadGagah** [comment]
mmm wait, when this option is turned off it still shows the same Traceback as in the first comment.

Enable advanced settings (including temperature and probability mass)  check box  not checked  Alt+a

Can this problem be fixed?
